### ISSUE TITLE
Use the scroll wheel to scroll media

### ISSUE THREAD

**Issue by gravelfreeman** [normen/obs-mcu#10]
This would be a dream come true. I can't remember how many times I had to scroll into a 10 minute video to show something different.

This one might be harder to accomplish since it would be hard to define which media source to scroll on to.

I think it could be solved by scrolling the media source that has SELECT enabled.

or

Use the latest triggered media source. Or both ideas together where the first one could override the latter.

**Comment by normen** [comment]
Very ugly, won't add

**Comment by normen** [comment]
Yeah, some more support for players (like the display stuff) on top of the basic shortcuts is probably in order.
