### ISSUE TITLE
Fader issue when switching between scenes

### ISSUE THREAD

**Issue by gravelfreeman** [normen/obs-mcu#12]
As you can see in this video, when I switch between scenes the faders will bring in the audio tracks from the next scene without removing the faders from the previous scene. This makes the faders moves 2 times instead of one.

I’m not sure what could be doing this. I know the OBS mixer is limited and the issue might come from there. I can see the new audio tracks appearing before the audio tracks from the previous scene disappear.

I wonder if there’s a way to overcome this issue. It gives the feeling that the equipment is broken.

To hack it in the meantime would it be possible to add a delay until the obs mixer is set before changing the faders layout?

https://github.com/user-attachments/assets/4e198714-3487-45f6-ae0b-f20480f0be04

**Comment by normen** [comment]
I see this happening sometimes, but with your set up, it seems to be very, very slow. I just see a single fader quickly flip sometimes when switching scenes. The faders are simply assigned in the order that OBS sends them. I could add a delay, but with your set up it seems like that would have to be unreasonably long.

**Comment by normen** [comment]
The existing sync delay of 100ms is now configurable through the config file. Start the app once to see the new parameter in the config.

**Comment by normen** [comment]
The new section wasn't loaded from the config file, should be fixed now.

**Comment by gravelfreeman** [comment]
> The new section wasn't loaded from the config file, should be fixed now.

Thank you so much! What a game changer. The audio mixer in OBS is really bad compared to DAWs and other apps I've been using with the X-Touch with.

Believe it or not but I add to set a value of `1400` for `sync_delay` so that it fixes the OBS mixer delay.
