### ISSUE TITLE
Audio meters not unloading

### ISSUE THREAD

**Issue by gravelfreeman** [normen/obs-mcu#13]
When ‘show_meters’ is set to true under [mcu_faders] in the configuration file the audio meters will not unload from the meter display in the previous channel where it was showing. This happens when you switch between scenes.

https://github.com/user-attachments/assets/59bfc8ef-f400-4111-bed5-131f5782dbb5

**Comment by normen** [comment]
Hm. Per the mackie control specs the MC should have a 300ms hold time and then reset to zero by itself if theres no more meter messages for that channel.. I suppose I have to tell some specifically to set the meter to zero (i.e. minus infinity)

**Comment by normen** [comment]
v0.7.12 should reset all unused meters even on control surfaces without built-in hold

**Comment by normen** [comment]
Can you check what the app displays for the version number when you start it? Theres a chance the windows binary is an old version in the releases.

**Comment by gravelfreeman** [comment]
It's working now thank you so much!
