### ISSUE TITLE
Questions and official docker image

### ISSUE THREAD

**Issue by gravelfreeman** [normen/obs-mcu#5]
First and foremost I want to thank you a billion time for coding this. I've been holding onto the X-Touch for so many years because it wasn't compatible with OBS. I might finally buy it. It would be awesome if you could do a small video showing how the tracks from OBS translates on the controller.

I'd like to be able to get the OBS track NAME and COLOR to work on the X-Touch. I got many different type of tracks that I color code and it would be a dream to get this information.

I'm not sure if this software could control audio filters and VST plugins PER track. For example I'd like to choose for example Track #1 and control the compressor gain on the Expander filter.

Another question I have is that I'm wondering if it would be possible to control my Behringer XR18 audio mixer and OBS at the same time. Or maybe I could switch between the 2 with a page button or something? Or is it more likely that I would need 2 X-Touch for each device?

Also it would be really nice if you could provide a docker image. Here in the studio, I got a server that runs every applications like Bitfocus Companion on docker. This makes it easier to deploy, use and is stable for production.

I'm very excited to see this plugin and I'm actually surprised there's not much traction about it on the forums.

Do you plan on supporting this for a long time?

Thank you again!

**Comment by normen** [comment]
Hi, thanks.

The OBS endpoint is a "Mackie Control" compatible one, meaning you're bound to what the Mackie Control protocol can do. Colors is not a part of that.

For controlling filters in OBS, I was looking into that but the remote support for detecting and selecting filters though the websockets plugin (which is what this application uses) is a bit lacking so thats probably for the future.

I don't know exactly what you mean by "tracks" but this application automatically controls the audio channels for the current program, i.e. exactly what the audio mixer in OBS shows.

Controlling the XR18 happens through a Network connection (I think, it does for my X32 Rack) with the Behringer Network protocol. This allows you to switch between the USB-Connected OBS and the Network-Connected XR on the surface of the X-Touch, which is exactly what I do in my studio where I use a X32Rack as the audio frontend for OBS.

As for docker, I don't know how docker handles USB connections and MIDI but I guess its a bit ugly to get that working so I'd leave people to their own devices there as I don't really want to get involved in that can of worms, getting hardware to connect properly is often hard enough as is.

Cheers,
Normen
