### ISSUE TITLE
Hidden state of audio channels

### ISSUE THREAD

**Issue by gravelfreeman** [normen/obs-mcu#6]
I think we should leave this issue open to track ideas and maybe someone will find and idea to hack this in some way.

From the documentation:

```
Theres afaict no way to get the "hidden" state of audio channels, so they will always display on the MCU even if they're hidden in OBS. As a workaround you can simply name these channels so that they appear all the way on the left and then press the "channel right" button until all channels you don't want to see are hidden.
```

The idea of hiding by pressing Channel Right button isn't practical since I don't have the same number of audio sources per scene depending on the number of speakers on screen.

In the meantime another workaround is to name your channel after the Z letter with a special character.

Here's a list of the characters that come immediately after "Z" in the ASCII table;

```
[ \ ] ^ _ ` { } ~
```

Hope we find a way around!

**Comment by normen** [comment]
I just put the channels that I need first and then ignore the others 🤷‍♂️
