### ISSUE TITLE
Unable to lighten the media control buttons

### ISSUE THREAD

**Issue by gravelfreeman** [normen/obs-mcu#8]
There are Rewind, Forward, Stop and Play buttons I remapped to control the media on screen instead of the default behaviour.

```
rewind           = KEY:VLCSource.PlaylistPrev,SlideShow.PreviousSlide
fast_fwd         = KEY:VLCSource.PlaylistNext,SlideShow.NextSlide
stop             = KEY:VLCSource.Stop,MediaSource.Stop,
play             = KEY:VLCSource.PlayPause,MediaSource.Play,MediaSource.Pause,SlideShow.PlayPause
record           = KEY:VLCSource.Restart,MediaSource.Restart,SlideShow.Restart
```

I would like to light the buttons but I can't seem to find how.

Ideally the Previous, Forward and Stop button would be a white color. The Play button could be green when playing, yellow when paused and white when stand by (stop). Since I'm using the Record button to restart it could be a red light.

Worst case would be to have all buttons lighten up. I have a hard time seeing those when there's no led on in them. I tried something like this without success:

```
rewind   = STATE:RecordState
fast_fwd = STATE:RecordState
stop     = STATE:RecordState
play     = STATE:RecordState
record   = STATE:RecordState
```

**Comment by normen** [comment]
For states only the rec and stream states are available, play and record light fine for me in the default setup, that not the case for you?

**Comment by normen** [comment]
So everything is working as intended

**Comment by normen** [comment]
I added an "AlwaysOn" state that is always on.

**Comment by normen** [comment]
Ah, okay. True, that is probably so 😄 But it shouldn't be, also not for normal mappings, which it probably is, too.

**Comment by normen** [comment]
Mhm, its not just a bug fix though, I have to save the mappings differently. Right now I save them in a map using the state name, so theres only one "slot" for each state basically.

**Comment by normen** [comment]
0.7.14 should fix this
